/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CookieConfig } from "./utils/telemetry-config";
export namespace Components {
    interface ArcgisPrivacyNotice {
        /**
          * Whether the notice is modal or footer
         */
        "view": "modal" | "popup";
    }
    interface ArcgisPrivacyOption {
    }
    interface ArcgisPrivacyPopup {
        /**
          * Visible state if open, or just showing cookie icon.
         */
        "open": boolean;
        /**
          * Whether the popup should popup or be inline
         */
        "view": "modal" | "popup";
    }
    interface ArcgisPrivacySettings {
        /**
          * Existing preference settings
         */
        "cookieConfig": CookieConfig;
        /**
          * Whether the Settings modal is open or closed
         */
        "open": boolean;
        /**
          * Explanation to show in window
         */
        "preferenceText": string;
    }
}
export interface ArcgisPrivacyPopupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArcgisPrivacyPopupElement;
}
export interface ArcgisPrivacySettingsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLArcgisPrivacySettingsElement;
}
declare global {
    interface HTMLArcgisPrivacyNoticeElement extends Components.ArcgisPrivacyNotice, HTMLStencilElement {
    }
    var HTMLArcgisPrivacyNoticeElement: {
        prototype: HTMLArcgisPrivacyNoticeElement;
        new (): HTMLArcgisPrivacyNoticeElement;
    };
    interface HTMLArcgisPrivacyOptionElement extends Components.ArcgisPrivacyOption, HTMLStencilElement {
    }
    var HTMLArcgisPrivacyOptionElement: {
        prototype: HTMLArcgisPrivacyOptionElement;
        new (): HTMLArcgisPrivacyOptionElement;
    };
    interface HTMLArcgisPrivacyPopupElement extends Components.ArcgisPrivacyPopup, HTMLStencilElement {
    }
    var HTMLArcgisPrivacyPopupElement: {
        prototype: HTMLArcgisPrivacyPopupElement;
        new (): HTMLArcgisPrivacyPopupElement;
    };
    interface HTMLArcgisPrivacySettingsElement extends Components.ArcgisPrivacySettings, HTMLStencilElement {
    }
    var HTMLArcgisPrivacySettingsElement: {
        prototype: HTMLArcgisPrivacySettingsElement;
        new (): HTMLArcgisPrivacySettingsElement;
    };
    interface HTMLElementTagNameMap {
        "arcgis-privacy-notice": HTMLArcgisPrivacyNoticeElement;
        "arcgis-privacy-option": HTMLArcgisPrivacyOptionElement;
        "arcgis-privacy-popup": HTMLArcgisPrivacyPopupElement;
        "arcgis-privacy-settings": HTMLArcgisPrivacySettingsElement;
    }
}
declare namespace LocalJSX {
    interface ArcgisPrivacyNotice {
        /**
          * Whether the notice is modal or footer
         */
        "view"?: "modal" | "popup";
    }
    interface ArcgisPrivacyOption {
    }
    interface ArcgisPrivacyPopup {
        "onOpenCookieDetails"?: (event: ArcgisPrivacyPopupCustomEvent<any>) => void;
        "onSetCookieConfig"?: (event: ArcgisPrivacyPopupCustomEvent<CookieConfig>) => void;
        /**
          * Visible state if open, or just showing cookie icon.
         */
        "open"?: boolean;
        /**
          * Whether the popup should popup or be inline
         */
        "view"?: "modal" | "popup";
    }
    interface ArcgisPrivacySettings {
        /**
          * Existing preference settings
         */
        "cookieConfig"?: CookieConfig;
        "onSetCookieConfig"?: (event: ArcgisPrivacySettingsCustomEvent<CookieConfig>) => void;
        /**
          * Whether the Settings modal is open or closed
         */
        "open"?: boolean;
        /**
          * Explanation to show in window
         */
        "preferenceText"?: string;
    }
    interface IntrinsicElements {
        "arcgis-privacy-notice": ArcgisPrivacyNotice;
        "arcgis-privacy-option": ArcgisPrivacyOption;
        "arcgis-privacy-popup": ArcgisPrivacyPopup;
        "arcgis-privacy-settings": ArcgisPrivacySettings;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "arcgis-privacy-notice": LocalJSX.ArcgisPrivacyNotice & JSXBase.HTMLAttributes<HTMLArcgisPrivacyNoticeElement>;
            "arcgis-privacy-option": LocalJSX.ArcgisPrivacyOption & JSXBase.HTMLAttributes<HTMLArcgisPrivacyOptionElement>;
            "arcgis-privacy-popup": LocalJSX.ArcgisPrivacyPopup & JSXBase.HTMLAttributes<HTMLArcgisPrivacyPopupElement>;
            "arcgis-privacy-settings": LocalJSX.ArcgisPrivacySettings & JSXBase.HTMLAttributes<HTMLArcgisPrivacySettingsElement>;
        }
    }
}
